source "https://rubygems.org"

gem "rails", "~> 8.1.2"
gem "puma", ">= 5"
gem "propshaft"
gem "sqlite3", ">= 2.1"
gem "importmap-rails"
gem "turbo-rails"
gem "stimulus-rails"
gem "bootsnap", require: false

gem "async-websocket"
gem "async-http"

# The engine under development
gem "wrap_it_ruby", path: ".."

group :development, :test do
  gem "debug", platforms: %i[mri windows], require: "debug/prelude"
end
